- hosts: all
  roles:
    - role: vitalk.secure-ssh
      ssh_identity_key: "{{ secure_ssh.ssh_identity_key }}"
      ssh_user: "{{ ansible_ssh_user }}"
      become: yes
      when: secure_ssh.enabled

    - role: routing
      become: yes
      when: routing.enabled
      tags: ["routing"]

    - role: geerlingguy.firewall
      become: yes
      when: routing.enabled

    - role: zerotier
      become: yes
      when: zerotier.enabled

    - role: motion
      become: yes
      when: motion.enabled
      tags: ["motion"]

    - role: rofs
      become: yes
      tags: ["rofs"]

    - role: geerlingguy.nfs
      when: nfs.enabled
      become: yes
      tags: ["nfs"]
